### PR TITLE
Bump compat for GPUArraysCore to 0.2, (keep existing compat)

### PR DESCRIPTION
**Pull request by fhagemann**
I also exchanged `using GPUArraysCore` with `import GPUArraysCore` and added the prefix `GPUArraysCore` everywhere where it is used (which seems to be only in one line in `transpose.jl`).

### CODE REVIEW

**Comment by fhagemann** [comment]
Failing Downgrade tests are due to `FillArrays<0.13` not being supported in `julia-1.11`.
I also expect the tests to still run on `GPUArraysCore@0.1.6` because `StructArrays` does not yet allow for `GPUArraysCore@0.2`.

**Comment by oschulz** [comment]
Tests still run on GPUArraysCore v0.2, some deps will need to update first.

**Comment by fhagemann** [comment]
#45 set the lowest version of FillArrays to `0.13` (probably because of julia-1.11 compatibility).
It should be `0.13.8` though. We should either revert #45 back to FillArrays 0.8.4 (and run downgrade on `julia-1.10`) or increase the lower bound to `0.13.8`. For this PR, I have chosen the latter.

**Comment by fhagemann** [comment]
Basically, this PR does what #46 is proposing.
I would recommend to do both at once and make a patch release.

**Comment by oschulz** [comment]
Test still use the old GPUArraysCore and StructArrays, looks like some deps need to update first.

**Comment by fhagemann** [comment]
Should be LegendDataTypes and LegendHDF5IO

**Comment by fhagemann** [comment]
That's because of RadiationDetectorSignals.

**Pull request merged**
