### PR TITLE
Implementation of DoublePolezerocorrection Filter

### PR DESCRIPTION
**Pull request by DaGeibl**
Added a filter that makes a double pole-zero correction possible.
Name of the filter maybe could be changed

### CODE REVIEW

**Comment by DaGeibl** [comment]
soll ich noch einen Test schreiben?

**Comment by oschulz** [comment]
> soll ich noch einen Test schreiben?

Thanks - yes, a test would be nice. Also, would it be possible to also add the "forward" filter?

**Comment by DaGeibl** [comment]
I have implemented the forward filter and wrote a test. Is the test fine like this?

**Comment by oschulz** [comment]
Very nice @DaGeibl . Could we rename `CRFilterSO` to `SecondOrderCRFilter` or similar? Would be more readable in code.

**Comment by oschulz** [comment]
Good to merge from your side @theHenks ?

**Comment by oschulz** [comment]
Ping @theHenks , good to merge from your side?

**Comment by theHenks** [comment]
Checked it on some waveforms here. Seems good from my side. 
I think tests are ready, too @oschulz ? And the inverse filter is also included. So good for me!

**Comment by oschulz** [comment]
@DaGeibl , sorry , could you just rename `SecondOrderInvCRFilter` to `InvSecondOrderCRFilter` before we merge?

**Comment by DaGeibl** [comment]
@oschulz  done

**Comment by oschulz** [comment]
Many thanks @DaGeibl !

**Comment by oschulz** [comment]
https://github.com/JuliaRegistries/General/pull/95774

**Pull request merged**
