### PR TITLE
Adjust lower compats for compatibility with julia-1.11

### PR DESCRIPTION
**Pull request by fhagemann**
Here are some changes to the lower package compats required to work on julia-1.11:
- The type parameter in `AbstractTriangular` was [removed in julia-1.11](https://github.com/JuliaLang/julia/pull/26307/commits/06d93f90a6cbc6352b9f05549abd955f6dd35fb2). 
As `AbstractTriangular` was explicitly called in `FillArrays` [until `0.13.8`](https://github.com/JuliaArrays/FillArrays.jl/compare/v0.13.7..v0.13.8#diff-d11a0a28fd067d4eebae26a3afe9eba608bc6285f91bf4bb2cde6f9a1720ecd3L353-R329),the compat in the General registry was manually adjusted to [disallow the use of `FillArrays` pre-`0.13` with julia-1.11](https://github.com/JuliaRegistries/General/commit/fae5d81639cff33a8616a32a019749253090a47f).
==> I adjusted the lower compat of `FillArrays` to `0.13.8`.

- `BinaryProvider` is [discontinued in julia-1.11](https://github.com/JuliaRegistries/General/commit/f6a651cb64114b0332d9df033acc6f1219143fb1).
  - `FFTW` directly depended on `BinaryProvider` [until `1.1`](https://github.com/JuliaRegistries/General/blob/master/F/FFTW/Compat.toml).
==> I adjusted the lower compat of `FFTW` to `1.2`. 
  - `SpecialFunctions` depended on `BinaryProvider` [until `0.8`](https://github.com/JuliaRegistries/General/blob/master/S/SpecialFunctions/Compat.toml). 
  In `RadiationDetectorDSP`, `DSP@0.6` only allows for `SpecialFunctions@0.8`.
  ==> I adjusted the lower compat of `DSP` to `0.6.2` to also allow for `SpecialFunctions@0.9`.

These changes should resolve the failing Downgrade tests.
The only question remaining: do we want an explicit version requirement for `SpecialFunctions ≥ 0.9` via weak dependencies here?

### CODE REVIEW

**Comment by oschulz** [comment]
> These changes should resolve the failing Downgrade tests.

Should we maybe run Downgrade on Julia v1.10 LTS - so kinda downgrade Julia as well?

**Comment by fhagemann** [comment]
We could. Or is there a possibility to have different Project.toml for each Julia version?

**Comment by oschulz** [comment]
> Or is there a possibility to have different Project.toml for each Julia version

No, that's not possible.

**Comment by fhagemann** [comment]
I relaxed the package compatibility requirements by setting `strict: false` in the `Downgrade` CI.

Final changes:
-  I adjusted the lower compat of `FillArrays` to `0.13`.
-  I adjusted the lower compat of `FFTW` to `1.2` to not depend on `BinaryProvider`.
- `Downgrade` will now run BOTH on `1.10` and on `1`.

@oschulz If all tests pass, this PR should be ready to go.

**Comment by fhagemann** [comment]
Done in #47

**Pull request closed without merging**
