### PR TITLE
Add gaussian filter and CUSP filter and resolve issues with zac filter

### PR DESCRIPTION
**Pull request by apmypb**
resolve normalization issue of zac filter

Add gaussian filter and CUSP filter

### CODE REVIEW

**Comment by oschulz** [comment]
CC @theHenks

**Comment by oschulz** [comment]
@apmypb can you take a look at the test failures?

**Comment by apmypb** [comment]
I changed the type conditions in the constructor of the ZAC filter so one can also use different types for the parameters and instead added a `promote_type` in the functions which create the coefficients. Is this fine with you @oschulz?

**Comment by oschulz** [comment]
> I changed the type conditions in the constructor of the ZAC filter so one can also use different types for the parameters

We shouldn't parameterize the type so heavily, at all adds compilation complexity. We need different types for parameters that describe different quantities, but parameters that have values of, e.g., time, should have the same type. We can still add convenience constructors that allow the user to pass different types and then promote and create the filter object.

**Comment by theHenks** [comment]
I can have a look later to check the filter. Or is no help from my side needed?

**Comment by apmypb** [comment]
I need some feedback regarding the new parameters for all filters.
I added an additional scaling factor and normalized the filter output, such that the sum of the coefficients stay constant regardless of the total length of the filter. If they work as intended, you can merge it.

**Comment by theHenks** [comment]
I had a discussion with Artur. The filters look fine for me, so I think it is ready to merge. 
@oschulz can you do that so that I can implement it into the routines? I would like to avoid to use the PR branch for production.

**Pull request merged**
